using System.Collections.Generic;
using System.Text;
using ZeroAlloc.Authorization.Generator.Diagnostics;
using ZeroAlloc.Authorization.Generator.Discovery;

namespace ZeroAlloc.Authorization.Generator.Emit;

internal static class AuthorizerForEmitter
{
    public static string Emit(
        IReadOnlyList<RequireInfo> requires,
        IReadOnlyDictionary<string, PolicyInfo> policiesByName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace ZeroAlloc.Authorization.Generated");
        sb.AppendLine("{");
        for (int i = 0; i < requires.Count; i++)
        {
            EmitOne(sb, requires[i], policiesByName);
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// ZAUTH007: the requirements <see cref="Emit"/> skips because their arguments do not fit the
    /// policy. At the attribute.
    /// </summary>
    public static void ReportArgShapeMismatches(
        IReadOnlyList<RequireInfo> requires,
        IReadOnlyDictionary<string, PolicyInfo> policiesByName,
        List<DiagnosticInfo> diagnostics)
    {
        foreach (var req in requires)
        {
            foreach (var group in req.Groups)
            {
                foreach (var (name, error) in ArgShapeErrors(group, policiesByName))
                {
                    diagnostics.Add(DiagnosticInfo.Create(
                        Descriptors.RequirePolicyArgShapeMismatch,
                        group.AttributeLocation,
                        name, req.FullyQualifiedTypeName, error));
                }
            }
        }
    }

    // The names in the group whose arguments do not fit their policy, and why. A name with no
    // policy is ZAUTH001's, not this one's.
    private static IEnumerable<(string Name, string Error)> ArgShapeErrors(
        RequireGroup group,
        IReadOnlyDictionary<string, PolicyInfo> policiesByName)
    {
        if (group.Kind == RequireGroupKind.All)
        {
            var name = group.PolicyNames[0];
            if (policiesByName.TryGetValue(name, out var policy) && ValidateArgShape(group.Args[0], policy) is { } error)
            {
                yield return (name, error);
            }
            yield break;
        }

        foreach (var name in group.PolicyNames)
        {
            // [RequireAnyPolicy] only accepts parameterless policies in v2.1.
            if (policiesByName.TryGetValue(name, out var policy) && policy.Arity != 0)
            {
                yield return (name, $"[RequireAnyPolicy] only accepts parameterless policies; '{name}' implements IAuthorizationPolicy<...>");
            }
        }
    }

    private static void EmitOne(
        StringBuilder sb,
        RequireInfo req,
        IReadOnlyDictionary<string, PolicyInfo> policiesByName)
    {
        sb.AppendLine($"    internal sealed class GeneratedAuthorizerFor_{req.SafeIdentifier}");
        sb.AppendLine($"        : global::ZeroAlloc.Authorization.AuthorizerFor<{req.FullyQualifiedTypeName}>");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.IServiceProvider _sp;");
        sb.AppendLine($"        public GeneratedAuthorizerFor_{req.SafeIdentifier}(global::System.IServiceProvider sp) => _sp = sp;");
        sb.AppendLine();
        sb.AppendLine("        public override async global::System.Threading.Tasks.ValueTask<global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>> EvaluateAsync(");
        sb.AppendLine("            global::ZeroAlloc.Authorization.ISecurityContext ctx,");
        sb.AppendLine("            global::System.Threading.CancellationToken ct = default)");
        sb.AppendLine("        {");
        // The locals of all groups share one scope. Two groups may name the same policy, and two
        // names may sanitize alike, so a local that is taken gets a numbered suffix.
        var locals = new HashSet<string>(System.StringComparer.Ordinal);
        for (int gi = 0; gi < req.Groups.Count; gi++)
        {
            var group = req.Groups[gi];
            if (group.Kind == RequireGroupKind.All)
            {
                EmitAllGroup(sb, group, policiesByName, locals);
            }
            else // Any
            {
                EmitAnyGroup(sb, req, group, gi, policiesByName, locals);
            }
        }
        sb.AppendLine("            return global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>.Success();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitAllGroup(
        StringBuilder sb,
        RequireGroup group,
        IReadOnlyDictionary<string, PolicyInfo> policiesByName,
        HashSet<string> locals)
    {
        var name = group.PolicyNames[0];
        if (!policiesByName.TryGetValue(name, out var policy)) return; // ZAUTH001 will diagnose
        var args = group.Args[0]; // null = parameterless; non-null = typed
        if (ValidateArgShape(args, policy) is not null) return; // ZAUTH007 will diagnose

        var local = UniqueLocal(locals, Sanitize(name));
        var argList = FormatArgsForDispatch(args);

        if (policy.Arity == 0)
        {
            sb.AppendLine($"            global::ZeroAlloc.Authorization.IAuthorizationPolicy __p_{local} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{policy.FullyQualifiedTypeName}>(_sp);");
        }
        else
        {
            var genericParamList = string.Join(", ", System.Linq.Enumerable.Select(policy.TypeArgs, ta => ta.FullyQualifiedName));
            sb.AppendLine($"            global::ZeroAlloc.Authorization.IAuthorizationPolicy<{genericParamList}> __p_{local} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{policy.FullyQualifiedTypeName}>(_sp);");
        }
        sb.AppendLine($"            var __r_{local} = await __p_{local}.EvaluateAsync(ctx{argList}, ct).ConfigureAwait(false);");
        sb.AppendLine($"            if (__r_{local}.IsFailure) return __r_{local};");
    }

    private static void EmitAnyGroup(
        StringBuilder sb,
        RequireInfo req,
        RequireGroup group,
        int groupIndex,
        IReadOnlyDictionary<string, PolicyInfo> policiesByName,
        HashSet<string> locals)
    {
        var groupId = req.SafeIdentifier + "_g" + groupIndex.ToString(System.Globalization.CultureInfo.InvariantCulture);
        sb.AppendLine();
        sb.AppendLine($"            // OR group {groupId}");

        var failureLocalNames = new List<string>();
        var failurePolicyNames = new List<string>();
        var seen = new HashSet<string>(System.StringComparer.Ordinal);
        foreach (var name in group.PolicyNames)
        {
            // A name listed twice is the same alternative; evaluating it once is enough.
            if (!seen.Add(name)) continue;
            if (!policiesByName.TryGetValue(name, out var policy)) continue;
            // [RequireAnyPolicy] only accepts parameterless policies in v2.1; ZAUTH007 diagnoses.
            if (policy.Arity != 0) continue;
            var local = UniqueLocal(locals, Sanitize(name) + "_" + groupId);
            failureLocalNames.Add(local);
            failurePolicyNames.Add(name);
            sb.AppendLine($"            global::ZeroAlloc.Authorization.IAuthorizationPolicy __p_{local} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{policy.FullyQualifiedTypeName}>(_sp);");
            sb.AppendLine($"            var __r_{local} = await __p_{local}.EvaluateAsync(ctx, ct).ConfigureAwait(false);");
            sb.AppendLine($"            if (__r_{local}.IsSuccess) goto __or_pass_{groupId};");
        }

        if (failureLocalNames.Count == 0)
        {
            sb.AppendLine($"            __or_pass_{groupId}: ;");
            return;
        }

        // All-fail synthesis.
        sb.Append("            return global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>.Failure(\n");
        sb.Append("                new global::ZeroAlloc.Authorization.AuthorizationFailure(\n");
        sb.Append("                    \"any.all_failed\",\n");
        sb.Append("                    $\"");
        for (int i = 0; i < failureLocalNames.Count; i++)
        {
            var pName = failurePolicyNames[i];
            var local = failureLocalNames[i];
            if (i > 0) sb.Append(" OR ");
            sb.Append("[").Append(pName).Append(": {__r_").Append(local).Append(".Error.Reason ?? __r_").Append(local).Append(".Error.Code}]");
        }
        sb.Append("\"));\n");
        sb.AppendLine($"            __or_pass_{groupId}: ;");
    }

    /// <summary>Returns null when args match policy.Arity/TypeArgs; otherwise returns a shape-error string for ZAUTH007.</summary>
    private static string? ValidateArgShape(EquatableArray<ConstantArg>? args, PolicyInfo policy)
    {
        var actualCount = args?.Count ?? 0;
        if (policy.Arity != actualCount)
        {
            var expectedSig = policy.Arity == 0
                ? "IAuthorizationPolicy"
                : $"IAuthorizationPolicy<{string.Join(", ", System.Linq.Enumerable.Select(policy.TypeArgs, ta => ta.DisplayName))}>";
            return $"expected {policy.Arity} argument(s) for {expectedSig}, got {actualCount}";
        }
        if (args is not { } actual) return null;
        for (int i = 0; i < actualCount; i++)
        {
            var expected = policy.TypeArgs[i];
            var actualType = actual[i].Type;
            if (actualType is null) return $"argument at position {i}: could not infer type";
            if (!string.Equals(actualType.Identity, expected.Identity, System.StringComparison.Ordinal))
            {
                return $"argument at position {i}: expected {expected.DisplayName}, got {actualType.DisplayName}";
            }
        }
        return null;
    }

    private static string FormatArgsForDispatch(EquatableArray<ConstantArg>? args)
    {
        if (args is not { Count: > 0 } values) return string.Empty;
        var sb = new StringBuilder();
        foreach (var c in values)
        {
            sb.Append(", ").Append(c.Literal);
        }
        return sb.ToString();
    }

    private static string UniqueLocal(HashSet<string> taken, string local)
    {
        var candidate = local;
        for (var n = 2; !taken.Add(candidate); n++)
        {
            candidate = local + "_" + n.ToString(System.Globalization.CultureInfo.InvariantCulture);
        }
        return candidate;
    }

    private static string Sanitize(string s)
    {
        var sb = new StringBuilder(s.Length);
        for (int i = 0; i < s.Length; i++)
        {
            var c = s[i];
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }
        return sb.ToString();
    }
}
