using System.Collections.Generic;
using System.Text;
using ZeroAlloc.Authorization.Generator.Discovery;

namespace ZeroAlloc.Authorization.Generator.Emit;

internal static class AuthorizerForEmitter
{
    public static string Emit(
        IReadOnlyList<RequireInfo> requires,
        IReadOnlyDictionary<string, PolicyInfo> policiesByName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace ZeroAlloc.Authorization.Generated");
        sb.AppendLine("{");
        for (int i = 0; i < requires.Count; i++)
        {
            EmitOne(sb, requires[i], policiesByName);
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitOne(
        StringBuilder sb,
        RequireInfo req,
        IReadOnlyDictionary<string, PolicyInfo> policiesByName)
    {
        sb.AppendLine($"    internal sealed class GeneratedAuthorizerFor_{req.SafeIdentifier}");
        sb.AppendLine($"        : global::ZeroAlloc.Authorization.AuthorizerFor<{req.FullyQualifiedTypeName}>");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.IServiceProvider _sp;");
        sb.AppendLine($"        public GeneratedAuthorizerFor_{req.SafeIdentifier}(global::System.IServiceProvider sp) => _sp = sp;");
        sb.AppendLine();
        sb.AppendLine("        public override async global::System.Threading.Tasks.ValueTask<global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>> EvaluateAsync(");
        sb.AppendLine("            global::ZeroAlloc.Authorization.ISecurityContext ctx,");
        sb.AppendLine("            global::System.Threading.CancellationToken ct = default)");
        sb.AppendLine("        {");
        for (int i = 0; i < req.PolicyNames.Count; i++)
        {
            var name = req.PolicyNames[i];
            if (!policiesByName.TryGetValue(name, out var policy)) continue; // ZAUTH001 will diagnose
            var local = Sanitize(name);
            // Type as IAuthorizationPolicy so the interface method dispatch is uniform across
            // policy implementations (even though only one method exists, the resolved type
            // is the concrete policy class — the interface cast keeps the call site stable).
            sb.AppendLine($"            global::ZeroAlloc.Authorization.IAuthorizationPolicy __p_{local} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{policy.FullyQualifiedTypeName}>(_sp);");
            sb.AppendLine($"            var __r_{local} = await __p_{local}.EvaluateAsync(ctx, ct).ConfigureAwait(false);");
            sb.AppendLine($"            if (__r_{local}.IsFailure) return __r_{local};");
        }
        sb.AppendLine("            return global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>.Success();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string Sanitize(string s)
    {
        var sb = new StringBuilder(s.Length);
        for (int i = 0; i < s.Length; i++)
        {
            var c = s[i];
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }
        return sb.ToString();
    }
}
