using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using ZeroAlloc.Authorization.Generator.Diagnostics;
using ZeroAlloc.Authorization.Generator.Discovery;

namespace ZeroAlloc.Authorization.Generator.Emit;

internal static class AuthorizerForEmitter
{
    public static string Emit(
        IReadOnlyList<RequireInfo> requires,
        IReadOnlyDictionary<string, PolicyInfo> policiesByName,
        List<Diagnostic> diagnostics)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace ZeroAlloc.Authorization.Generated");
        sb.AppendLine("{");
        for (int i = 0; i < requires.Count; i++)
        {
            EmitOne(sb, requires[i], policiesByName, diagnostics);
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitOne(
        StringBuilder sb,
        RequireInfo req,
        IReadOnlyDictionary<string, PolicyInfo> policiesByName,
        List<Diagnostic> diagnostics)
    {
        sb.AppendLine($"    internal sealed class GeneratedAuthorizerFor_{req.SafeIdentifier}");
        sb.AppendLine($"        : global::ZeroAlloc.Authorization.AuthorizerFor<{req.FullyQualifiedTypeName}>");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.IServiceProvider _sp;");
        sb.AppendLine($"        public GeneratedAuthorizerFor_{req.SafeIdentifier}(global::System.IServiceProvider sp) => _sp = sp;");
        sb.AppendLine();
        sb.AppendLine("        public override async global::System.Threading.Tasks.ValueTask<global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>> EvaluateAsync(");
        sb.AppendLine("            global::ZeroAlloc.Authorization.ISecurityContext ctx,");
        sb.AppendLine("            global::System.Threading.CancellationToken ct = default)");
        sb.AppendLine("        {");
        foreach (var group in req.Groups)
        {
            if (group.Kind == RequireGroupKind.All)
            {
                EmitAllGroup(sb, req, group, policiesByName, diagnostics);
            }
            // Kind=Any: Task 7
        }
        sb.AppendLine("            return global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>.Success();");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitAllGroup(
        StringBuilder sb,
        RequireInfo req,
        RequireGroup group,
        IReadOnlyDictionary<string, PolicyInfo> policiesByName,
        List<Diagnostic> diagnostics)
    {
        var name = group.PolicyNames[0];
        if (!policiesByName.TryGetValue(name, out var policy)) return; // ZAUTH001 will diagnose
        var args = group.Args[0]; // null = parameterless; non-null = typed

        var argShapeError = ValidateArgShape(args, policy);
        if (argShapeError is not null)
        {
            diagnostics.Add(Diagnostic.Create(
                Descriptors.RequirePolicyArgShapeMismatch,
                group.AttributeLocation,
                name, req.FullyQualifiedTypeName, argShapeError));
            return;
        }

        var local = Sanitize(name);
        var argList = FormatArgsForDispatch(args);

        if (policy.Arity == 0)
        {
            sb.AppendLine($"            global::ZeroAlloc.Authorization.IAuthorizationPolicy __p_{local} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{policy.FullyQualifiedTypeName}>(_sp);");
        }
        else
        {
            var genericParamList = string.Join(", ", System.Linq.Enumerable.Select(policy.TypeArgs, ta => ta.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
            sb.AppendLine($"            global::ZeroAlloc.Authorization.IAuthorizationPolicy<{genericParamList}> __p_{local} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{policy.FullyQualifiedTypeName}>(_sp);");
        }
        sb.AppendLine($"            var __r_{local} = await __p_{local}.EvaluateAsync(ctx{argList}, ct).ConfigureAwait(false);");
        sb.AppendLine($"            if (__r_{local}.IsFailure) return __r_{local};");
    }

    /// <summary>Returns null when args match policy.Arity/TypeArgs; otherwise returns a shape-error string for ZAUTH007.</summary>
    private static string? ValidateArgShape(IReadOnlyList<TypedConstant>? args, PolicyInfo policy)
    {
        var actualCount = args?.Count ?? 0;
        if (policy.Arity != actualCount)
        {
            var expectedSig = policy.Arity == 0
                ? "IAuthorizationPolicy"
                : $"IAuthorizationPolicy<{string.Join(", ", System.Linq.Enumerable.Select(policy.TypeArgs, ta => ta.ToDisplayString()))}>";
            return $"expected {policy.Arity} argument(s) for {expectedSig}, got {actualCount}";
        }
        if (args is null) return null;
        for (int i = 0; i < actualCount; i++)
        {
            var expected = policy.TypeArgs[i];
            var actualType = args[i].Type;
            if (actualType is null) return $"argument at position {i}: could not infer type";
            if (!SymbolEqualityComparer.Default.Equals(actualType, expected))
            {
                return $"argument at position {i}: expected {expected.ToDisplayString()}, got {actualType.ToDisplayString()}";
            }
        }
        return null;
    }

    private static string FormatArgsForDispatch(IReadOnlyList<TypedConstant>? args)
    {
        if (args is null || args.Count == 0) return string.Empty;
        var sb = new StringBuilder();
        foreach (var c in args)
        {
            sb.Append(", ").Append(FormatConstant(c));
        }
        return sb.ToString();
    }

    private static string FormatConstant(TypedConstant c)
    {
        return c.Kind switch
        {
            TypedConstantKind.Primitive => c.Value switch
            {
                string s   => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"",
                char ch    => $"'{ch}'",
                bool b     => b ? "true" : "false",
                null       => "null",
                _          => System.FormattableString.Invariant($"{c.Value!}"),
            },
            TypedConstantKind.Enum => $"({c.Type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}){c.Value}",
            _ => "default",
        };
    }

    private static string Sanitize(string s)
    {
        var sb = new StringBuilder(s.Length);
        for (int i = 0; i < s.Length; i++)
        {
            var c = s[i];
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }
        return sb.ToString();
    }
}
