using System.Collections.Generic;
using System.Text;
using ZeroAlloc.Authorization.Generator.Discovery;

namespace ZeroAlloc.Authorization.Generator.Emit;

internal static class DIRegistrationEmitter
{
    public static string Emit(
        IReadOnlyList<PolicyInfo> policies,
        IReadOnlyList<RequireInfo> requires)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace ZeroAlloc.Authorization.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    public static class GeneratedAuthorizationRegistration");
        sb.AppendLine("    {");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddZeroAllocAuthorization(");
        sb.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");
        for (int i = 0; i < policies.Count; i++)
        {
            var policy = policies[i];
            if (!policy.IsInstantiable) continue;
            sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<{policy.FullyQualifiedTypeName}>(services);");
        }
        for (int i = 0; i < requires.Count; i++)
        {
            var req = requires[i];
            sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::ZeroAlloc.Authorization.AuthorizerFor<{req.FullyQualifiedTypeName}>, global::ZeroAlloc.Authorization.Generated.GeneratedAuthorizerFor_{req.SafeIdentifier}>(services);");
        }
        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
