//HintName: ZeroAllocAuthorization.Generated.g.cs
// <auto-generated/>
#nullable enable
namespace ZeroAlloc.Authorization.Generated
{
    internal sealed class GeneratedAuthorizerFor_MyApp_DeleteUser
        : global::ZeroAlloc.Authorization.AuthorizerFor<global::MyApp.DeleteUser>
    {
        private readonly global::System.IServiceProvider _sp;
        public GeneratedAuthorizerFor_MyApp_DeleteUser(global::System.IServiceProvider sp) => _sp = sp;

        public override async global::System.Threading.Tasks.ValueTask<global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>> EvaluateAsync(
            global::ZeroAlloc.Authorization.ISecurityContext ctx,
            global::System.Threading.CancellationToken ct = default)
        {
            global::ZeroAlloc.Authorization.IAuthorizationPolicy __p_admin = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::SharedKernel.AdminPolicy>(_sp);
            var __r_admin = await __p_admin.EvaluateAsync(ctx, ct).ConfigureAwait(false);
            if (__r_admin.IsFailure) return __r_admin;
            return global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>.Success();
        }
    }

}
// <auto-generated/>
#nullable enable
namespace ZeroAlloc.Authorization.Generated
{
    public static class GeneratedAuthorizationRegistration
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddZeroAllocAuthorization(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::SharedKernel.AdminPolicy>(services);
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::ZeroAlloc.Authorization.AuthorizerFor<global::MyApp.DeleteUser>, global::ZeroAlloc.Authorization.Generated.GeneratedAuthorizerFor_MyApp_DeleteUser>(services);
            return services;
        }
    }
}
