//HintName: ZeroAllocAuthorization.Generated.g.cs
// <auto-generated/>
#nullable enable
namespace ZeroAlloc.Authorization.Generated
{
    internal sealed class GeneratedAuthorizerFor_MyApp_ApplyForLicenseCommand
        : global::ZeroAlloc.Authorization.AuthorizerFor<global::MyApp.ApplyForLicenseCommand>
    {
        private readonly global::System.IServiceProvider _sp;
        public GeneratedAuthorizerFor_MyApp_ApplyForLicenseCommand(global::System.IServiceProvider sp) => _sp = sp;

        public override async global::System.Threading.Tasks.ValueTask<global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>> EvaluateAsync(
            global::ZeroAlloc.Authorization.ISecurityContext ctx,
            global::System.Threading.CancellationToken ct = default)
        {
            global::ZeroAlloc.Authorization.IAuthorizationPolicy<int> __p_MinAge = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::MyApp.MinAgePolicy>(_sp);
            var __r_MinAge = await __p_MinAge.EvaluateAsync(ctx, 18, ct).ConfigureAwait(false);
            if (__r_MinAge.IsFailure) return __r_MinAge;
            return global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>.Success();
        }
    }

}
// <auto-generated/>
#nullable enable
namespace ZeroAlloc.Authorization.Generated
{
    public static class GeneratedAuthorizationRegistration
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddZeroAllocAuthorization(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::MyApp.MinAgePolicy>(services);
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::ZeroAlloc.Authorization.AuthorizerFor<global::MyApp.ApplyForLicenseCommand>, global::ZeroAlloc.Authorization.Generated.GeneratedAuthorizerFor_MyApp_ApplyForLicenseCommand>(services);
            return services;
        }
    }
}
