//HintName: ZeroAllocAuthorization.Generated.g.cs
// <auto-generated/>
#nullable enable
namespace ZeroAlloc.Authorization.Generated
{
    internal sealed class GeneratedAuthorizerFor_MyApp_ReadDocCommand
        : global::ZeroAlloc.Authorization.AuthorizerFor<global::MyApp.ReadDocCommand>
    {
        private readonly global::System.IServiceProvider _sp;
        public GeneratedAuthorizerFor_MyApp_ReadDocCommand(global::System.IServiceProvider sp) => _sp = sp;

        public override async global::System.Threading.Tasks.ValueTask<global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>> EvaluateAsync(
            global::ZeroAlloc.Authorization.ISecurityContext ctx,
            global::System.Threading.CancellationToken ct = default)
        {
            global::ZeroAlloc.Authorization.IAuthorizationPolicy<string, int> __p_Permission = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::MyApp.PermissionPolicy>(_sp);
            var __r_Permission = await __p_Permission.EvaluateAsync(ctx, "read", 42, ct).ConfigureAwait(false);
            if (__r_Permission.IsFailure) return __r_Permission;
            return global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>.Success();
        }
    }

}
// <auto-generated/>
#nullable enable
namespace ZeroAlloc.Authorization.Generated
{
    public static class GeneratedAuthorizationRegistration
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddZeroAllocAuthorization(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::MyApp.PermissionPolicy>(services);
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::ZeroAlloc.Authorization.AuthorizerFor<global::MyApp.ReadDocCommand>, global::ZeroAlloc.Authorization.Generated.GeneratedAuthorizerFor_MyApp_ReadDocCommand>(services);
            return services;
        }
    }
}
