//HintName: ZeroAllocAuthorization.Generated.g.cs
// <auto-generated/>
#nullable enable
namespace ZeroAlloc.Authorization.Generated
{
    internal sealed class GeneratedAuthorizerFor_MyApp_ViewBillingQuery
        : global::ZeroAlloc.Authorization.AuthorizerFor<global::MyApp.ViewBillingQuery>
    {
        private readonly global::System.IServiceProvider _sp;
        public GeneratedAuthorizerFor_MyApp_ViewBillingQuery(global::System.IServiceProvider sp) => _sp = sp;

        public override async global::System.Threading.Tasks.ValueTask<global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>> EvaluateAsync(
            global::ZeroAlloc.Authorization.ISecurityContext ctx,
            global::System.Threading.CancellationToken ct = default)
        {
            global::ZeroAlloc.Authorization.IAuthorizationPolicy __p_Admin = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::MyApp.AdminPolicy>(_sp);
            var __r_Admin = await __p_Admin.EvaluateAsync(ctx, ct).ConfigureAwait(false);
            if (__r_Admin.IsFailure) return __r_Admin;

            // OR group MyApp_ViewBillingQuery_g1
            global::ZeroAlloc.Authorization.IAuthorizationPolicy __p_Premium_MyApp_ViewBillingQuery_g1 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::MyApp.PremiumPolicy>(_sp);
            var __r_Premium_MyApp_ViewBillingQuery_g1 = await __p_Premium_MyApp_ViewBillingQuery_g1.EvaluateAsync(ctx, ct).ConfigureAwait(false);
            if (__r_Premium_MyApp_ViewBillingQuery_g1.IsSuccess) goto __or_pass_MyApp_ViewBillingQuery_g1;
            global::ZeroAlloc.Authorization.IAuthorizationPolicy __p_Trusted_MyApp_ViewBillingQuery_g1 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::MyApp.TrustedPolicy>(_sp);
            var __r_Trusted_MyApp_ViewBillingQuery_g1 = await __p_Trusted_MyApp_ViewBillingQuery_g1.EvaluateAsync(ctx, ct).ConfigureAwait(false);
            if (__r_Trusted_MyApp_ViewBillingQuery_g1.IsSuccess) goto __or_pass_MyApp_ViewBillingQuery_g1;
            return global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>.Failure(
                new global::ZeroAlloc.Authorization.AuthorizationFailure(
                    "any.all_failed",
                    $"[Premium: {__r_Premium_MyApp_ViewBillingQuery_g1.Error.Reason ?? __r_Premium_MyApp_ViewBillingQuery_g1.Error.Code}] OR [Trusted: {__r_Trusted_MyApp_ViewBillingQuery_g1.Error.Reason ?? __r_Trusted_MyApp_ViewBillingQuery_g1.Error.Code}]"));
            __or_pass_MyApp_ViewBillingQuery_g1: ;
            return global::ZeroAlloc.Results.UnitResult<global::ZeroAlloc.Authorization.AuthorizationFailure>.Success();
        }
    }

}
// <auto-generated/>
#nullable enable
namespace ZeroAlloc.Authorization.Generated
{
    public static class GeneratedAuthorizationRegistration
    {
        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddZeroAllocAuthorization(
            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
        {
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::MyApp.AdminPolicy>(services);
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::MyApp.PremiumPolicy>(services);
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::MyApp.TrustedPolicy>(services);
            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<global::ZeroAlloc.Authorization.AuthorizerFor<global::MyApp.ViewBillingQuery>, global::ZeroAlloc.Authorization.Generated.GeneratedAuthorizerFor_MyApp_ViewBillingQuery>(services);
            return services;
        }
    }
}
